services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mafcode-backend
    ports:
      - "9000:9000"
    env_file:
      - ./.env
    networks:
      - app-network
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mafcode-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
